version: "3.9"

services:
  validator-1:
    build: .
    command: ["--port", "47701"]
    volumes:
      - taxoin-java-data-1:/app/.taxoin
    environment:
      - TAXOIN_VALIDATOR=1
      - TAXOIN_PORT=47701
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:47701/q/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  validator-2:
    build: .
    command: ["--port", "47702"]
    volumes:
      - taxoin-java-data-2:/app/.taxoin
    environment:
      - TAXOIN_VALIDATOR=2
      - TAXOIN_PORT=47702
    depends_on:
      validator-1:
        condition: service_healthy

  validator-3:
    build: .
    command: ["--port", "47703"]
    volumes:
      - taxoin-java-data-3:/app/.taxoin
    environment:
      - TAXOIN_VALIDATOR=3
      - TAXOIN_PORT=47703
    depends_on:
      validator-1:
        condition: service_healthy

  api:
    build: .
    command: ["--port", "47780"]
    ports:
      - "47780:47780"
    volumes:
      - taxoin-java-data-api:/app/.taxoin
    environment:
      - TAXOIN_API=1
      - TAXOIN_PORT=47780
    depends_on:
      - validator-1
      - validator-2
      - validator-3

volumes:
  taxoin-java-data-1:
  taxoin-java-data-2:
  taxoin-java-data-3:
  taxoin-java-data-api:
